Feature/gestione gruppi
gps-is-2019/amigo pull request #5
Opened 2019-12-29 11:35 UTC by GitJoedg

2019-12-30 10:16 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/controller/GruppoController.java
> +        model.addAttribute("isCapogruppo", gruppoService.isResponsabile(personaLoggata.getId(), idSupergruppo));
```suggestion
        model.addAttribute("isResponsabile", gruppoService.isResponsabile(personaLoggata.getId(), idSupergruppo));
```
Così l'attributo è consistente con il nome del metodo

2019-12-30 10:58 UTC, mdestefano requested changes
Il lavoro va sommariamente bene. Non c'è un buon uso del polimorfismo e la strategia della gerarchia per gruppo e commissioni non viene usata al meglio. Molti metodi sono una "duplicazione di codice" perché non essendo polimorfici, sono le stesse operazioni sia per gruppo che per commissione, che in realtà condividono lo stesso "padre" e che quindi potrebbero usate, per alcune operazioni, indistintamente.

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/controller/GruppoController.java
> +    public String findAllMembriInGruppoNoCommissione(@PathVariable(name = "idSupergruppo") int idSupergruppo, Model model){
```suggestion
    public String groupCandidatesList(@PathVariable(name = "idSupergruppo") int idSupergruppo, Model model){
```

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/controller/GruppoController.java
> +    }
Se gruppi e commissioni sono in una gerarchia, perché creare due metedi diversi per visualizare i dettagli e i membri del gruppo/commissione? Non sarebbe meglio creare un metodo polimorfico? (anche nel service)

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/controller/GruppoController.java
> +    }
Non si può rendere il metodo di eliminazione del gruppo polimorfico e, come sopra, usare lo stesso metodo sia per gruppo che per commissione?

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/controller/GruppoController.java
> +    @PostMapping("/gruppi/{idGruppo}/commissioni/createCommissione")
```suggestion
    @PostMapping("/gruppi/{idGruppo}/commissioni/create")
```
Si può usere lo stesso url di quello che mostra il form, perché sono mapati su due metodi HTTP diversi.

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/controller/GruppoController.java
> +    @GetMapping("/gruppi/commissioni/{idCommissione}/nominaResponsabile/{idPersona}")
Perché usare un metodo GET  e passare tutti sti parametri da url? Non è meglio creare un metodo mappato su POST che accetta la sottomissione da un form e creare un piccolo form in-line che sottomette il valore?

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/dao/CommissioneDAO.java
> +}
Non avevamo detto che usavamo la singola tabella su db per la gerarchia? perchè  c'e una dao apposita?

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/domain/Supergruppo.java
> +
```suggestion
```

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/domain/Supergruppo.java
> +import lombok.experimental.SuperBuilder;
```suggestion
```

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoService.java
> +    Persona getAuthenticatedUser();
Si potrebbe spostare in un altro service, magari in autenticazione, e restituire un oggetto di tipo user e da lì navigare la relazione e ottenere la persona. Per ora lasciamolo qua.

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoServiceImpl.java
> +    public List<Supergruppo> findAllSupergruppi(int idPersona) {
```suggestion
    public List<Supergruppo> findAllSupergruppiOfPersona(int idPersona) {
```
Quando cambiate il nome usate il refactoring di intelliJ che lo cambia anche nell''interfaccia.

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoServiceImpl.java
> +    public List<ConsiglioDidattico> findAllConsigliDidattici(int idPersona) {
```suggestion
    public List<ConsiglioDidattico> findAllConsigliDidatticiOfPersona(int idPersona) {
```

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoServiceImpl.java
> +    public List<Dipartimento> findAllDipartimenti(int idPersona) {
```suggestion
    public List<Dipartimento> findAllDipartimentiOfPersona(int idPersona) {
```

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoServiceImpl.java
> +    private final GruppoDAO gruppoDAO;
Non si usa autowired nei services. Meglio la dependency injection con costruttore.

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoService.java
>  public interface GruppoService {
Stavo pensando di dividere in due il service, quello che ha a che fare strettamente con le persone, e quello che ha a che fare solamente con creazione di gruppi e commissioni. Il primo prenderebbe tutti i metodi che restituiscono persone e il secondo la creazione, l'aggiunta, la creazione e la nomina di responsabili.
**DA VALUTARE, NON SI DEVE FARE PER FORZA ORA**.

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoServiceImpl.java
> +    }
Polimorfico?

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoServiceImpl.java
> +    }
Polimorfico?

2019-12-30 10:58 UTC, mdestefano commented on src/main/java/it/unisa/Amigo/gruppo/services/GruppoServiceImpl.java
> +    }
Polimorfico?

2019-12-30 12:51 UTC, emaiannone commented on src/test/java/it/unisa/Amigo/gruppo/controller/GruppoControllerTest.java
>          when(gruppoService.findSupergruppo(expectedSupergruppo.getId())).thenReturn(expectedSupergruppo);
Una domanda, a che serve l'attributo "type" in Supergruppo? A distinguere se è Gruppo o Commissione?

2019-12-30 13:22 UTC, emaiannone commented on src/test/java/it/unisa/Amigo/gruppo/controller/GruppoControllerTest.java
> +    void findAllSupergruppi() throws Exception {
Inoltre, questo è solo un caso di test di un singolo metodo. Forse è un po' pochino. Vedete come fare i test parametrici: https://www.baeldung.com/parameterized-tests-junit-5

2019-12-30 13:22 UTC, emaiannone commented on src/test/java/it/unisa/Amigo/gruppo/controller/GruppoControllerTest.java
> +    void findAllSupergruppi() throws Exception {
Così da aumentare il numero di casi di test con poco codice e poco sforzo

2019-12-30 13:24 UTC, emaiannone commented on src/test/java/it/unisa/Amigo/gruppo/services/GruppoServiceImplTest.java
> +    private GruppoDAO gruppoDAO;
Come per il test del controller, userei @MockBean di Spring stesso, che non fa altro che wrappare mockito. Più che altro è per un fatto di allineamento con gli altri test.

2019-12-30 13:25 UTC, emaiannone reviewed
Tutto sommato i test sembrano buoni. Bisogna solo aumentare il numero dei casi di test con i test parametrici. Inoltre, chiedo per tutte le classi (anche non di test) di lasciare il formatter di IntelliJ e di pulire il codice da righe vuote e spazi di troppo.

2019-12-30 21:24 UTC, emaiannone commented
![](https://github.trello.services/images/mini-trello-icon.png) [AI[50] - Implementazione RF_3.4 a 3.7](https://trello.com/c/cOzVkr84/93-ai50-implementazione-rf34-a-37)

2020-01-02 11:09 UTC, mdestefano approved these changes

2020-01-02 11:12 UTC, merged